LoadModule fcgid_module modules/mod_fcgid.so

ScriptAlias /smokeping/smokeping.cgi /var/www/localhost/smokeping/smokeping.cgi
Alias /smokeping/Core_API_TCP.rrd /data/Roblox_TCP/Core_API_TCP.rrd
Alias /smokeping /var/www/localhost/smokeping

<Directory "/var/www/localhost/smokeping">
    Options +ExecCGI
    AddHandler fcgid-script .cgi
    Options +FollowSymLinks
    Require all granted
</Directory>

<Directory "/data/Roblox_TCP">
    Require all granted
</Directory>
